" gvim options
:set guioptions-=m  " remove menu bar
:set guioptions-=T  " remove toolbar
:set guioptions-=r  " remove right-hand scroll bar
:set guioptions-=R
:set guioptions-=l  " remove left-hand scroll bar
:set guioptions-=L
:set guioptions-=b  " remove bottom scroll bar
:set guioptions-=B

" local vim config
if filereadable(expand("~/.gvimrc.local"))
  source ~/.gvimrc.local
endif
