" gvim options
:set guioptions-=m  " remove menu bar
:set guioptions-=T  " remove toolbar
:set guioptions-=r  " remove right-hand scroll bar
:set guioptions-=R
:set guioptions-=l  " remove left-hand scroll bar
:set guioptions-=L
:set guioptions-=b  " remove bottom scroll bar
:set guioptions-=B

" remap code completion to Ctrl+Space (gvim needs <C-space> instead of <Nul>)
inoremap <C-space> <C-x><C-o>

" local vim config
if filereadable(expand("~/.gvimrc.local"))
  source ~/.gvimrc.local
endif
