syntax on

set nocompatible
set number
set exrc         " enable per-directory .vimrc files
set secure       " disable unsafe commands in local .vimrc files

set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set expandtab
set smartindent
set autoindent

" highlight searches
set hlsearch
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR> " space disables highlighting

" default encoding
set encoding=utf-8

" no backup files
set nobackup
set nowritebackup

# pathogen setup
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin on

" tab completion
set wildchar=<Tab> wildmenu wildmode=full
set wildignore+=*.o,*.obj,*.rbc,.git,.bzr,.svn,*.pyc,*.jpg,*.jpeg,*.png,*.gif

" CommandT plugin
map <silent> <C-T> :CommandT<CR>
let g:CommandTMaxHeight=20

" Default color scheme
color desert

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" enable auto-completion
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS

" automatically remove trailing whitespace when saving
" remember cursor position when removing trailing whitespace
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd BufWritePre *.py call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.js call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.css call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.html call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.ammo call <SID>StripTrailingWhitespaces()

" python
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=grey guibg=grey
match ExtraWhitespace /\s\+$|\t/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * highlight ExtraWhitespace ctermbg=grey guibg=grey
autocmd BufWinLeave * call clearmatches()

" local config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
