syntax on

set statusline=%f%m\ %{fugitive#statusline()}\ %y%=%c,%l\ [%p%%]
set guicursor=n-c-v:blinkon0

set nocompatible
set number
set exrc         " enable per-directory .vimrc files
set secure       " disable unsafe commands in local .vimrc files

set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set expandtab
set smartindent
set autoindent

" always display statusline
set laststatus=2

" highlight searches
set hlsearch
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR> " space disables highlighting

" default encoding
set encoding=utf-8

" no backup files
set nobackup
set nowritebackup

" pathogen setup
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin on

" tab completion
set wildchar=<Tab> wildmenu wildmode=full
set wildignore+=*.o,*.obj,*.rbc,.git,.bzr,.svn,*.pyc,*.jpg,*.jpeg,*.png,*.gif

" Default color scheme
color desert

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" enable auto-completion
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS

" python
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=grey guibg=grey
match ExtraWhitespace /\s\+$|\t/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * highlight ExtraWhitespace ctermbg=grey guibg=grey
autocmd BufWinLeave * call clearmatches()

" local config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

