syntax on

set nocompatible
set number
":set cursorline " highlight current line
set exrc         " enable per-directory .vimrc files
set secure       " disable unsafe commands in local .vimrc files

set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set expandtab
set smartindent
set autoindent

" highlight search terms
set hlsearch
" press space to turn off highlighting
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" default encoding
set encoding=utf-8

" no backup files
set nobackup
set nowritebackup

filetype plugin on

set wildchar=<Tab> wildmenu wildmode=full
set wildignore+=*.o,*.obj,*.rbc,.git,*.pyc,*.jpg,*.jpeg,*.png,*.gif

" CommandT plugin
map <silent> <C-T> :CommandT<CR>
let g:CommandTMaxHeight=20

" build ctags for current dir
map <F8> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" enable auto-completion
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS

" Remap code completion to Ctrl+Space
" inoremap <Nul> <C-x><C-o>

" automatically remove trailing whitespace when saving

" remember cursor position when removing trailing whitespace
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd BufWritePre *.py call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.js call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.css call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.html call <SID>StripTrailingWhitespaces()
autocmd BufWritePre *.ammo call <SID>StripTrailingWhitespaces()

" python
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" html
autocmd BufRead *.ammo set filetype=html

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=grey guibg=grey
match ExtraWhitespace /\s\+$|\t/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * highlight ExtraWhitespace ctermbg=grey guibg=grey
autocmd BufWinLeave * call clearmatches()
